// <auto-generated />
using MasterCard.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MasterCard.Data.Migrations
{
    [DbContext(typeof(MasterCardContext))]
    [Migration("20241017064613_SeedDatabas")]
    partial class SeedDatabas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MasterCard.Domain.Cards.Card", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CardCategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CardCategoryId");

                    b.ToTable("CadModels", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CardCategoryId = 1L,
                            Description = "نسخه جدید (سازگار با مرورگرهای گوگل کروم و فایرفاکس)",
                            Icon = "https://localhost:7143/images/SiteIcons/chargoon.png",
                            IsDeleted = false,
                            Link = "http://office5.miu.ir",
                            Title = "سامانه اتوماسیون اداری نسخه 5"
                        },
                        new
                        {
                            Id = 2L,
                            CardCategoryId = 1L,
                            Description = "",
                            Icon = "https://localhost:7143/images/SiteIcons/foodCourt.png",
                            IsDeleted = false,
                            Link = "https://food.miu.ac.ir",
                            Title = "سامانه تغذیه"
                        },
                        new
                        {
                            Id = 3L,
                            CardCategoryId = 1L,
                            Description = "گردشگری، تسهیلات، هدایا و بیمه",
                            Icon = "https://localhost:7143/images/SiteIcons/workers.png",
                            IsDeleted = false,
                            Link = "http://irefah.miu.ir/",
                            Title = "سامانه رفاهی کارکنان"
                        },
                        new
                        {
                            Id = 4L,
                            CardCategoryId = 1L,
                            Description = "پست الکترونیک سازمانی المصطفی (مدیران، اساتید و کارکنان)",
                            Icon = "https://localhost:7143/images/SiteIcons/electronic.png",
                            IsDeleted = false,
                            Link = "https://mail.miu.ac.ir",
                            Title = "پست الکترونیک المصطفی"
                        });
                });

            modelBuilder.Entity("MasterCard.Domain.Cards.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("CardCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsDeleted = false,
                            Title = "ریاست"
                        },
                        new
                        {
                            Id = 2L,
                            IsDeleted = false,
                            Title = "معاونت آموزش"
                        },
                        new
                        {
                            Id = 3L,
                            IsDeleted = false,
                            Title = "معاونت فرهنگی تربیتی"
                        },
                        new
                        {
                            Id = 4L,
                            IsDeleted = false,
                            Title = "معاونت پژوهش"
                        },
                        new
                        {
                            Id = 5L,
                            IsDeleted = false,
                            Title = "معاونت بین الملل"
                        });
                });

            modelBuilder.Entity("MasterCard.Domain.Cards.Card", b =>
                {
                    b.HasOne("MasterCard.Domain.Cards.Category", "Category")
                        .WithMany("Cards")
                        .HasForeignKey("CardCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MasterCard.Domain.Cards.Category", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
